### ISSUE TITLE
Flag is not changing with phone number

### ISSUE THREAD

**Issue by babitakapoor112** [rili-live/react-native-phone-input#1]
Hi, 
I am facing a problem while changing my phone number. when I pick a country from the modal Picker and tries to change my phon number then sometimes the phone number does not reflect with that country code. Also, my flag got vanish from the input. Please see the below screenshot

![image](https://user-images.githubusercontent.com/45659052/108027275-edd7c400-704f-11eb-8716-5ae6ad5b0082.png)
![image](https://user-images.githubusercontent.com/45659052/108027355-0ea01980-7050-11eb-96d8-fa67afe34af1.png)

**Comment by kkbhati18** [comment]
pls enter cerroct contry code

**Comment by zizzle6717** [comment]
Please make a pull request. I have taken ownership of this repo because the previous publisher stopped following up. I'm happy to check and publish updates, but I don't have much time to dedicate to the project development at this time. I will try to work on the development more when my schedule fees up.

**Comment by zizzle6717** [comment]
This has been resolve with the latest PRs. I've also fixed the autoFormat property.
